Repository hay-i/gooal, pull requests merged in 2024-06, with the labels that each got.

#70 Design System / Styling
  assets/fonts/Satoshi-Bold.otf
  assets/fonts/Satoshi-Medium.otf
  assets/fonts/Synonym-Regular.otf
  assets/scss/abstracts/_fonts.scss
  assets/scss/abstracts/_variables.scss
  assets/scss/components/_buttons.scss
  assets/scss/components/_draggable.scss
  assets/scss/components/_questionnaire.scss
  assets/scss/components/_splash.scss
  assets/scss/core/_globals.scss
  assets/scss/core/_typography.scss
  assets/scss/layouts/_footer.scss
  assets/scss/layouts/_header.scss
  assets/scss/styles.css
  assets/scss/styles.css.map
  assets/scss/styles.scss
  assets/svg/finance.svg
  assets/svg/fitness.svg
  assets/svg/logo-white.svg
  assets/svg/logo.svg
  assets/svg/social.svg
  assets/svg/splash-bg.svg
  components/base.templ
  components/base_templ.go
  components/button.templ
  components/button_templ.go
  components/footer.templ
  components/footer_templ.go
  components/home.templ
  components/home_templ.go
  components/questionnaire.templ
  components/questionnaire_templ.go
  components/users.templ
  components/users_templ.go
Labels: enhancement

#72 Add some better documentation + readme details
  README.md
  docs/dev.md
Labels: documentation

#80 Error handling for the template builder
  Makefile
  docs/dev.md
  internal/assets/js/main.js
  internal/components/templates.templ
  internal/components/templates_templ.go
  internal/controllers/answers/answers_controller.go
  internal/controllers/templates/templates_controller.go
  internal/db/read.go
  internal/db/write.go
  internal/form/parser/parser.go
  internal/form/validator/validator.go
  internal/formparser/validations.go
  internal/models/answer.go
  internal/models/question.go
  internal/models/question_answer.go
  internal/models/template.go
  internal/models/transformer.go
  internal/models/views/question.go
  internal/models/views/question_answer.go
  internal/models/views/template.go
  internal/router/init.go
  pkg/logger/logger.go
Labels: enhancement

#82 Include params on `return_to`
  internal/controllers/middleware/jwt.go
Labels: bug
